# Generated by Django 3.2.5 on 2021-07-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMICH', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenidos',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
