# Generated by Django 3.2.5 on 2021-07-16 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMICH', '0002_auto_20210716_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidos',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contenidos',
            name='tema',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
