# Generated by Django 3.2.5 on 2021-07-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMICH', '0003_auto_20210716_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenidos',
            options={'verbose_name': 'servicio', 'verbose_name_plural': 'servicios'},
        ),
        migrations.AlterField(
            model_name='contenidos',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contenidos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='contenidosMedia'),
        ),
    ]
