# Generated by Django 3.2.5 on 2021-07-17 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMICH', '0004_auto_20210716_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenidos',
            options={'verbose_name': 'contenido', 'verbose_name_plural': 'contenidos'},
        ),
    ]
