# Generated by Django 3.2.5 on 2021-07-19 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMICH', '0006_contactos'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactos',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactos',
            name='tipo_consulta',
            field=models.IntegerField(choices=[[0, 'consulta'], [1, 'sugerencia'], [2, 'saludo'], [3, 'varios']], default=0),
            preserve_default=False,
        ),
    ]
