# Generated by Django 3.2.5 on 2021-07-19 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMICH', '0007_auto_20210719_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactos',
            options={'verbose_name': 'contacto', 'verbose_name_plural': 'contactos'},
        ),
        migrations.RenameField(
            model_name='contactos',
            old_name='tipo_consulta',
            new_name='tipo_de_consulta',
        ),
    ]
