# Generated by Django 3.2.5 on 2021-07-21 13:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMICH', '0008_auto_20210719_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenidos',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
