# Generated by Django 3.2.5 on 2021-07-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMICH', '0009_alter_contenidos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenidos',
            name='cuerpo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contenidos',
            name='subtitulo',
            field=models.CharField(max_length=150),
        ),
    ]
